name: 'AutoOAS diff'
description: 'Runs OpenAPI-diff on multiple profile specifications'
inputs:
  profiles:
    default: 'default'
  old_dir:
    required: true
  new_dir:
    required: true

runs:
  using: 'composite'
  steps:
    - name: 'Run OpenAPI-diff'
      run: |
        OLD_FILES=$(find "$OLD_DIR" -type f | sed "s|$OLD_DIR/||" | sort)
        NEW_FILES=$(find "$NEW_DIR" -type f | sed "s|$NEW_DIR/||" | sort)
        
        COMMON_FILES=$(comm -12 <(echo "$OLD_FILES") <(echo "$NEW_FILES"))
        
        for p in ${COMMON_FILES[@]}; do
            STATUS=$(docker run --rm -t \
                -v $(pwd):/specs \
                openapitools/openapi-diff:latest --state --markdown "/specs/$p.md" /specs/$OLD_DIR/$p /specs/$NEW_DIR/$p)
            
            [ "$STATUS" != "no_changes" ] && echo "Changes: $STATUS"
        done
        
      shell: bash
      env:
        OLD_DIR: ${{inputs.old_dir}}
        NEW_DIR: ${{inputs.new_dir}}
