name: 'AutoOAS diff'
description: 'Runs OpenAPI-diff on multiple profile specifications'
inputs:
  profiles:
    default: 'default'
  old_dir:
    required: true
  new_dir:
    required: true

runs:
  using: 'composite'
  steps:
    - name: 'Run OpenAPI-diff'
      run: |
        EMPTY_OAS='{  "openapi" : "3.0.1",  "info" : {    "title" : "",    "description" : "Spring Profile: ???",    "version" : ""  },  "paths" : {  },  "components" : {    "schemas" : {    }  }}'

        echo $EMPTY_OAS > empty.json
        
        OLD_FILES=$(find "$OLD_DIR" -type f | sed "s|$OLD_DIR/||" | sort)
        NEW_FILES=$(find "$NEW_DIR" -type f | sed "s|$NEW_DIR/||" | sort)
        
        COMMON_FILES=$(comm -12 <(echo "$OLD_FILES") <(echo "$NEW_FILES"))
        OTHER_FILES=$(comm -3 <(echo "$OLD_FILES") <(echo "$NEW_FILES"))
        
        
        STATUS=0
        
        mkdir oas_diff
        
        echo "Analyzing existing configurations"
        for p in ${COMMON_FILES[@]}; do
            docker run --rm -t \
                -v $(pwd):/specs \
                openapitools/openapi-diff:latest --fail-on-incompatible --html "/specs/oas_diff/$p.html" /specs/$OLD_DIR/$p /specs/$NEW_DIR/$p > /dev/null
            EXIT_CODE=$?
            STATUS=$((STATUS + EXIT_CODE))
        done
        
        for p in ${OTHER_FILES[@]}; do
            if [ -f "$OLD_DIR/$p" ]; then
                echo "Analyzing deleted configurations"
                docker run --rm -t \
                    -v $(pwd):/specs \
                    openapitools/openapi-diff:latest --fail-on-incompatible --html "/specs/oas_diff/$p.html" /specs/$OLD_DIR/$p /specs/empty.json > /dev/null
                EXIT_CODE=$?
                STATUS=$((STATUS + EXIT_CODE))
            else
                echo "Analyzing added configurations"
                docker run --rm -t \
                    -v $(pwd):/specs \
                    openapitools/openapi-diff:latest --fail-on-incompatible --html "/specs/oas_diff/$p.html" /specs/empty.json /specs/$NEW_DIR/$p > /dev/null
                EXIT_CODE=$?
                STATUS=$((STATUS + EXIT_CODE))
            fi
        done
        
        echo $STATUS
      shell: bash
      env:
        OLD_DIR: ${{inputs.old_dir}}
        NEW_DIR: ${{inputs.new_dir}}
    
    - name: 'Upload specifications'
      uses: actions/upload-artifact@v4
      with:
        name: 'OpenAPI differences'
        path: oas_diff/*.html
