name: 'AutoOAS diff'
description: 'Runs OpenAPI-diff on multiple profile specifications'
inputs:
  profiles:
    default: 'default'
  old_dir:
    required: true
  new_dir:
    required: true

runs:
  using: 'composite'
  steps:
    
    - name: 'Run OpenAPI-diff'
      run: openapi_diff.sh
      shell: bash
