name: 'AutoOAS diff'
description: 'Runs OpenAPI-diff on multiple profile specifications'
inputs:
  profiles:
    default: 'default'
  old_dir:
    required: true
  new_dir:
    required: true

runs:
  using: 'composite'
  steps:
    - name: 'Run OpenAPI-diff'
      id: 'diff_step'
      run: |
        set +e
        
        OLD_FILES=$(find "$OLD_DIR" -type f | sed "s|$OLD_DIR/||" | sort)
        NEW_FILES=$(find "$NEW_DIR" -type f | sed "s|$NEW_DIR/||" | sort)
        
        COMMON_FILES=$(comm -12 <(echo "$OLD_FILES") <(echo "$NEW_FILES"))
        OTHER_FILES=$(comm -3 <(echo "$OLD_FILES") <(echo "$NEW_FILES"))
        
        STATUS=0
        
        mkdir oas_diff
        
        echo "Analyzing existing configurations"
        for p in ${COMMON_FILES[@]}; do
            docker run --rm -t \
                -v $(pwd):/specs \
                openapitools/openapi-diff:latest --fail-on-incompatible --html "/specs/oas_diff/$p.html" /specs/$OLD_DIR/$p /specs/$NEW_DIR/$p > /dev/null
            EXIT_CODE=$?
            STATUS=$((STATUS + EXIT_CODE))
        done
        
        for p in ${OTHER_FILES[@]}; do
            if [ -f "$OLD_DIR/$p" ]; then
                echo "Analyzing deleted configurations"
                docker run --rm -t \
                    -v $(pwd):/specs \
                    openapitools/openapi-diff:latest --fail-on-incompatible --html "/specs/oas_diff/$p.html" /specs/$OLD_DIR/$p /specs/empty_oas.json > /dev/null
                EXIT_CODE=$?
                STATUS=$((STATUS + EXIT_CODE))
            else
                echo "Analyzing added configurations"
                docker run --rm -t \
                    -v $(pwd):/specs \
                    openapitools/openapi-diff:latest --fail-on-incompatible --html "/specs/oas_diff/$p.html" /specs/empty_oas.json /specs/$NEW_DIR/$p > /dev/null
                EXIT_CODE=$?
                STATUS=$((STATUS + EXIT_CODE))
            fi
        done
        
        set -e
        
        echo "status=$STATUS" >> "$GITHUB_OUTPUT"
      shell: bash
      env:
        OLD_DIR: ${{inputs.old_dir}}
        NEW_DIR: ${{inputs.new_dir}}
    - name: 'Upload specifications'
      uses: actions/upload-artifact@v4
      with:
        name: 'OpenAPI differences'
        path: oas_diff/*.html
    - name: 'Check breaking info'
      shell: bash
      run: |
        if [ "${{steps.diff_step.outputs.status}}" -gt 0 ]; then 
          echo "::error::Breaking changes detected"
          exit 1
        fi
