name: 'AutoOAS diff'
description: 'Runs OpenAPI-diff on multiple profile specifications'
inputs:
  profiles:
    default: 'default'
  old_dir:
    required: true
  new_dir:
    required: true

runs:
  using: 'composite'
  steps:
    - name: 'Run OpenAPI-diff'
      run: |
        OLD_FILES=$(find "$OLD_DIR" -type f | sed "s|$OLD_DIR/||" | sort)
        NEW_FILES=$(find "$NEW_DIR" -type f | sed "s|$NEW_DIR/||" | sort)
        
        COMMON_FILES=$(comm -12 <(echo "$OLD_FILES") <(echo "$NEW_FILES"))
        STATUS=0
        for p in ${COMMON_FILES[@]}; do
            docker run --rm -t \
                -v $(pwd):/specs \
                openapitools/openapi-diff:latest --fail-on-incompatible --html "/specs/$p.html" /specs/$OLD_DIR/oas_diff/$p /specs/$NEW_DIR/oas_diff/$p > /dev/null
            EXIT_CODE=$?
            STATUS=$((STATUS + EXIT_CODE))
        done
        
        if [ $STATUS -ge 1 ]; then
            echo "::error title={Breaking changes}::{There are breaking changes in the OAS specifications}"
            exit 1
        fi
      shell: bash
      env:
        OLD_DIR: ${{inputs.old_dir}}
        NEW_DIR: ${{inputs.new_dir}}
    
    - name: 'Upload specifications'
    uses: actions/upload-artifact@v4
    with:
      name: 'OpenAPI differences'
      path: oas_diff/*.html
